language: ruby

dist: trusty

sudo:
    false
    
rvm:
  - 2.4
  - 2.3
  - 2.2

matrix:
    allow_failures:
    - rvm: 2.2

install:
  - gem install authorizenet
  - bundle install


script: 
  - bundle exec rspec spec/sample_code_spec.rb
